export const courses_fcas = [

  // ==================== MONDAY (day: 1) ====================

  {
    courseCode: "BIO 102",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Dr. Akoun/Mrs Oluwajimi",
    venue: "LT",
  },
  {
    courseCode: "CHM 410",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Olaniran/Ms Olayemi",
    venue: "LO",
  },
  {
    courseCode: "MCB 328",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Ms. Oloruntoba",
    venue: "MBL",
  },
  {
    courseCode: "MTH 202",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Ajayi",
    venue: "CAS 1",
  },
  {
    courseCode: "DOM-CYB 202",
    programme: ["cyber security"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mrs Ogundipe",
    venue: "SL",
  },
  {
    courseCode: "CSC 310",
    programme: ["computer science"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Ms Aromavo",
    venue: "CAS 2",
  },
  {
    courseCode: "COS 202",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Ms Ayediran",
    venue: "LT",
  },
  {
    courseCode: "SEN 410",
    programme: ["software engineering"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Ige",
    venue: "CAS 3",
  },
  {
    courseCode: "CSC 404",
    programme: ["computer science"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Ms Aromavo",
    venue: "HL",
  },
  {
    courseCode: "MCB 412",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr. Ikejiama",
    venue: "MBL",
  },
  {
    courseCode: "BCH 302",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr John",
    venue: "CAS 2",
  },
  {
    courseCode: "CHM 304",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mrs Oyelahan",
    venue: "LO",
  },
  {
    courseCode: "DOM-MCB 206",
    programme: ["microbiology"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mrs Olayinka",
    venue: "CAS 1",
  },
   {
    courseCode: "CHM 422",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Olaniran",
    venue: "LO",
  },
  {
    courseCode: "BCH 418",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr Olojo",
    venue: "LO",
  },
  {
    courseCode: "CHM 108/DOM-CHM 108",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "17:00" }],
    lecturer: "Mrs Hassan",
    venue: "CSL",
  },
  {
    courseCode: "CHM 356",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Ms Olayemi",
    venue: "LO",
  },
  {
    courseCode: "BCH 306",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Mr Adeyeye",
    venue: "CAS 2",
  },
  {
    courseCode: "DOM-MCB 204",
    programme: ["microbiology"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Ms. Oloruntoba",
    venue: "MBL",
  },
  {
    courseCode: "CSC 494/CYB 412/SEN 412",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "15:00" }],
    lecturer: "ALL CSC LECTURERS",
    venue: "SL",
  },
  {
    courseCode: "CSC 408/SEN 308",
    programme: ["computer science", "software engineering"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "15:00", endTime: "16:00" }],
    lecturer: "Mr Ige",
    venue: "SL",
  },
  {
    courseCode: "ZOO 312",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Oluwajinmi",
    venue: "MBL",
  },
  {
    courseCode: "MCB 322",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "14:00", endTime: "15:00" }],
    lecturer: "Dr. Ikiejiam",
    venue: "CAS 1",
  },

  // ==================== TUESDAY (day: 2) ====================

//   {
//     courseCode: "CHM 422",
//     programme: ["biochemistry"],
//     level: "400",
//     dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
//     lecturer: "Mr Olaniran",
//     venue: "LO",
//   },
//   {
//     courseCode: "BCH 418",
//     programme: ["biochemistry"],
//     level: "400",
//     dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
//     lecturer: "Dr Olojo",
//     venue: "LO",
//   },
  {
    courseCode: "GST 112",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing", "public health", "MLS", "accounting", "business administration", "economics", "mass communication", "criminology and security studies", "industrial and personnel management"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Dr. Imaledo",
    venue: "LT",
  },
  {
    courseCode: "MCB 404",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Prof. Adegoke",
    venue: "LO",
  },
  {
    courseCode: "MCB 326",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr. Moses",
    venue: "CAS 1",
  },
  {
    courseCode: "BCH 306",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Adeyeye",
    venue: "CAS 2",
  },
  {
    courseCode: "BCH 310",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Dr Olojo",
    venue: "CSL",
  },
  {
    courseCode: "DOM-CHM 254",
    programme: ["biochemistry"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Ms Olayemi",
    venue: "FBR",
  },
  {
    courseCode: "DOM-CSC 206",
    programme: ["computer science"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "09:15", endTime: "10:15" }],
    lecturer: "Mr Muritala",
    venue: "HL",
  },
  {
    courseCode: "BCH 202",
    programme: ["biochemistry"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr. Olaleye/Mr Akinboro",
    venue: "LT",
  },
  {
    courseCode: "COS 102",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Muritala",
    venue: "CAS 3",
  },
  {
    courseCode: "MCB 332",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Prof. Adegoke",
    venue: "MBL",
  },
  {
    courseCode: "CHM 406",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mrs Oyelahan",
    venue: "LO",
  },
  {
    courseCode: "BCH 408",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr. Olojo",
    venue: "CSL",
  },
  {
    courseCode: "SEN 402",
    programme: ["software engineering"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Ogundipe",
    venue: "HL",
  },
  {
    courseCode: "BIO 108",
    programme: ["microbiology", "biochemistry", "nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Mrs Oyelahan",
    venue: "MBL",
  },
  {
    courseCode: "DOM-CHM 210",
    programme: ["biochemistry"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Mr Olaniran",
    venue: "CSL",
  },
  {
    courseCode: "ZOO 312",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Mrs Oluwajinmi",
    venue: "CAS 1",
  },
  {
    courseCode: "ZOO 412",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "15:00", endTime: "16:00" }],
    lecturer: "Mrs Olayinka",
    venue: "CAS 1",
  },
  {
    courseCode: "CHM 316",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Mrs Oyelahan",
    venue: "LO",
  },
  {
    courseCode: "SEN 102",
    programme: ["software engineering"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Ige",
    venue: "CAS 3",
  },
  {
    courseCode: "COS 202",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "15:00" }],
    lecturer: "Ms Ayediran",
    venue: "SL",
  },
  {
    courseCode: "COS 302",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Ms Ayediran",
    venue: "SL",
  },
  {
    courseCode: "CYB 404/SEN 414",
    programme: ["cyber security", "software engineering"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Ogundipe",
    venue: "HL",
  },
  {
    courseCode: "CYB 406",
    programme: ["cyber security"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Barr. Adetoyinbo",
    venue: "SL",
  },

  // ==================== WEDNESDAY (day: 3) ====================

  {
    courseCode: "CSC 482/SEN 318",
    programme: ["computer science", "software engineering"],
    level: "400",
    dayAndTime: [
      { day: 2, startTime: "08:15", endTime: "10:15" },
      
    ],
    lecturer: "Ms Aromavo",
    venue: "CAS 3",
  },
  {
    courseCode: "INS 204",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "15:00", endTime: "16:00" }],
    lecturer: "Mr Muritala",
    venue: "FBR",
  },
  {
    courseCode: "CSC 408/SEN 308",
    programme: ["computer science", "software engineering"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Mr Ige",
    venue: "CAS 3",
  },
  {
    courseCode: "GST 212",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing", "public health", "MLS", "accounting", "business administration", "economics", "mass communication", "criminology and security studies", "industrial and personnel management"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Dr. Imaledo",
    venue: "LT",
  },
  {
    courseCode: "SEN 406",
    programme: ["software engineering"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Ige",
    venue: "SL",
  },
  {
    courseCode: "CYB 408",
    programme: ["cyber security"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mrs Ogundipe",
    venue: "HL",
  },
  {
    courseCode: "MCB 424",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr. Itor",
    venue: "CAS 1",
  },
  {
    courseCode: "CHM 252",
    programme: ["biochemistry"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Ms Olayemi",
    venue: "LO",
  },
  {
    courseCode: "BCH 404",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Dr Olaleye",
    venue: "CSL",
  },
  {
    courseCode: "MTH 102/DOM-NSC 102",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Ajayi",
    venue: "LT",
  },
  {
    courseCode: "CSC 492/CYB 492/SEN 492",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "12:15" }],
    lecturer: "ALL CSC LECTURERS",
    venue: "LO",
  },
  {
    courseCode: "MCB 322",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr. Ikejiama",
    venue: "MBL",
  },
  {
    courseCode: "MCB 408",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr. Taylor",
    venue: "CAS 1",
  },
  {
    courseCode: "CHM 358",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr Olojo",
    venue: "LO",
  },
  {
    courseCode: "CSC 302",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "300",
    dayAndTime: [
      { day: 2, startTime: "10:15", endTime: "12:15" },
      { day: 3, startTime: "13:00", endTime: "14:00" },
    ],
    lecturer: "Ms Ayediran",
    venue: "SL",
  },
  {
    courseCode: "PHY 108",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "17:00" }],
    lecturer: "Mr Iwasokun",
    venue: "HL",
  },
  {
    courseCode: "SEN 410",
    programme: ["software engineering"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Ige",
    venue: "CAS 3",
  },
  {
    courseCode: "DOM-CYB 202",
    programme: ["cyber security"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Ogundipe",
    venue: "HL",
  },
//   {
//     courseCode: "CSC 302",
//     programme: ["computer science"],
//     level: "300",
//     dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
//     lecturer: "Ms Ayediran",
//     venue: "SL",
//   },
  {
    courseCode: "CSC 308",
    programme: ["computer science"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Ms Aromavo",
    venue: "SL",
  },
  {
    courseCode: "CHM 254/DOM-CHM 203",
    programme: ["biochemistry"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Ms Olayemi",
    venue: "LO",
  },
  {
    courseCode: "MCB 326",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "15:00" }],
    lecturer: "Mr. Itor",
    venue: "CAS 1",
  },
  {
    courseCode: "BCH 412",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "15:00", endTime: "16:00" }],
    lecturer: "Mr Akinboro/Mr John",
    venue: "CAS 1",
  },
  {
    courseCode: "MCB 412",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Ikejiama",
    venue: "CAS 1",
  },

  // ==================== THURSDAY (day: 4) ====================

  {
    courseCode: "BCH 314",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Akinboro",
    venue: "CAS 2",
  },
  {
    courseCode: "SSC 202",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Ms Ayediran/Mr Egor",
    venue: "SL",
  },
  {
    courseCode: "BCH 406",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Adeyeye",
    venue: "CSL",
  },
  {
    courseCode: "BCH 308",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr Olaleye",
    venue: "CAS 3",
  },
  {
    courseCode: "DOM-BCH 212",
    programme: ["biochemistry"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Akinboro/Mr John",
    venue: "CAS 2",
  },
  {
    courseCode: "CHM 400",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "16:00" }],
    lecturer: "All Lecturers",
    venue: "LO",
  },
  {
    courseCode: "BCH 312",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Mr Adeyeye",
    venue: "CAS 2",
  },
  {
    courseCode: "CHM 492",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "16:00" }],
    lecturer: "All lecturers",
    venue: "LO",
  },
  {
    courseCode: "BCH 490",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "16:00" }],
    lecturer: "All lecturers",
    venue: "LO",
  },
  {
    courseCode: "CHM 420",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Dr olojo/Mrs oyelahan",
    venue: "LO",
  },
  {
    courseCode: "CHM 308",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Mrs Hassan",
    venue: "CSL",
  },
  {
    courseCode: "CHM 454",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "15:00" }],
    lecturer: "Ms Olayemi",
    venue: "LO",
  },
  {
    courseCode: "PHY 102",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Iwasokun",
    venue: "LT",
  },
  {
    courseCode: "CSC 318",
    programme: ["computer science", "cyber security"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Dr Ayeni",
    venue: "HL",
  },
  {
    courseCode: "DOM-CSC 208",
    programme: ["computer science"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Muritala",
    venue: "CAS 2",
  },
  {
    courseCode: "DOM-CYB 204",
    programme: ["cyber security"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Okunlola",
    venue: "FBR",
  },
  {
    courseCode: "BCH 402",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Akinboro",
    venue: "CAS 1",
  },
  {
    courseCode: "CHM 322",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr Olaniran",
    venue: "LO",
  },
  {
    courseCode: "MCB 414",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "10:15" }],
    lecturer: "Mr. Itor",
    venue: "MBL",
  },
  {
    courseCode: "BCH 318",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "10:15" }],
    lecturer: "D. Olaleye/Mr Adeyeye",
    venue: "CSL",
  },
  {
    courseCode: "IFT 212",
    programme: ["software engineering"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr Ayeni",
    venue: "HL",
  },
  {
    courseCode: "CSC 332",
    programme: ["computer science"],
    level: "300",
    dayAndTime: [
      { day: 3, startTime: "08:15", endTime: "10:15" },
    ],
    lecturer: "Mr Muritala",
    venue: "CAS 3",
  },
  {
    courseCode: "CSC 332",
    programme: ["computer science"],
    level: "300",
    dayAndTime: [
      { day: 4, startTime: "10:15", endTime: "12:15" }
    ],
    lecturer: "Mr Muritala",
    venue: "CAS 3",
  },
  {
    courseCode: "CYB 410",
    programme: ["cyber security"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Okunlola",
    venue: "LT",
  },
  {
    courseCode: "SEN 408",
    programme: ["software engineering"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Ige",
    venue: "SL",
  },
  {
    courseCode: "BTG 202",
    programme: ["biochemistry", "microbiology"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr. Akoun",
    venue: "CAS 1",
  },
  {
    courseCode: "MCB 324",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Dr. Taylor",
    venue: "MBL",
  },
  {
    courseCode: "CHM 312",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mrs Hassan/Mr Olaniran",
    venue: "LO",
  },
  {
    courseCode: "BCH 414",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Adeyeye",
    venue: "CSL",
  },
  {
    courseCode: "BCH 304",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "12:15" }],
    lecturer: "Mr Akinboro",
    venue: "CAS 2",
  },
  {
    courseCode: "DOM-MCB 102/DOM-NSC/MLS 104",
    programme: ["microbiology", "nursing", "MLS"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Dr. Taylor/Mrs Olayinka",
    venue: "LT",
  },
  {
    courseCode: "CHM 212",
    programme: ["biochemistry"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "16:00" }],
    lecturer: "Ms Olayemi",
    venue: "CSL",
  },
  {
    courseCode: "BCH 412",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr John Oladipo/Mr Akinboro",
    venue: "CAS 1",
  },
  {
    courseCode: "CSC 316",
    programme: ["computer science"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr Ayeni",
    venue: "HL",
  },
  {
    courseCode: "CHM 316",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Oyelahan",
    venue: "LO",
  },
  {
    courseCode: "CHM 304",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "15:00" }],
    lecturer: "Mrs Oyelahan",
    venue: "LO",
  },
  {
    courseCode: "MCB 424",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Itor",
    venue: "CAS 2",
  },
//   {
//     courseCode: "CHM 400",
//     programme: ["biochemistry"],
//     level: "400",
//     dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
//     lecturer: "All Lecturers",
//     venue: "LO",
//   },
//   {
//     courseCode: "BCH 312",
//     programme: ["biochemistry"],
//     level: "300",
//     dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
//     lecturer: "Mr Adeyeye",
//     venue: "CAS 2",
//   },
//   {
//     courseCode: "CHM 492",
//     programme: ["biochemistry"],
//     level: "400",
//     dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
//     lecturer: "All lecturers",
//     venue: "LO",
//   },
//   {
//     courseCode: "BCH 490",
//     programme: ["biochemistry"],
//     level: "400",
//     dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
//     lecturer: "All lecturers",
//     venue: "LO",
//   },
//   {
//     courseCode: "CHM 420",
//     programme: ["biochemistry"],
//     level: "400",
//     dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
//     lecturer: "Dr Olojo/Mrs Oyelahan",
//     venue: "LO",
//   },
//   {
//     courseCode: "CHM 308",
//     programme: ["biochemistry"],
//     level: "300",
//     dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
//     lecturer: "Mrs Hassan",
//     venue: "CSL",
//   },
//   {
//     courseCode: "CHM 454",
//     programme: ["biochemistry"],
//     level: "400",
//     dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
//     lecturer: "Ms Olayemi",
//     venue: "LO",
//   },
  {
    courseCode: "DOM-SEN 202",
    programme: ["software engineering"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "16:00", endTime: "18:00" }],
    lecturer: "Dr Ayeni",
    venue: "CAS 1",
  },

  // ==================== FRIDAY (day: 5) ====================

  {
    courseCode: "CSC 310",
    programme: ["computer science"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "9:15" }],
    lecturer: "Ms Aromavo",
    venue: "HL",
  },
  {
    courseCode: "CSC 406",
    programme: ["computer science", "software engineering"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "09:15", endTime: "10:15" }],
    lecturer: "Ms Ayediran",
    venue: "SL",
  },
  {
    courseCode: "SEN 306",
    programme: ["computer science", "software engineering"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "09:15", endTime: "10:15" }],
    lecturer: "Ms Ayediran",
    venue: "SL",
  },
  {
    courseCode: "INS 204",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Muritala",
    venue: "CAS 3",
  },
  {
    courseCode: "DOM-SEN 102",
    programme: ["software engineering"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Mr Ige",
    venue: "CAS 3",
  },
  {
    courseCode: "CSC 404",
    programme: ["computer science"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Ms Ayediran",
    venue: "SL",
  },
  {
    courseCode: "SSC 202",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "09:15", endTime: "10:15" }],
    lecturer: "Ms Ayediran",
    venue: "LO",
  },
  {
    courseCode: "CHM 102/DOM-CHM 102",
    programme: ["computer science", "cyber security", "software engineering", "biochemistry", "microbiology", "nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr John/Mrs Oyelahan",
    venue: "LT",
  },
  {
    courseCode: "CHM 454",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Ms Olayemi",
    venue: "LO",
  },
  {
    courseCode: "ZOO 412",
    programme: ["microbiology"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mrs Olayinka",
    venue: "MBL",
  },
  {
    courseCode: "CYB 404",
    programme: ["cyber security"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Okunlola",
    venue: "CAS 1",
  },
  {
    courseCode: "CSC 492/CYB 492/SEN 492",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "12:00" }],
    lecturer: "ALL CSC LECTURERS",
    venue: "SL",
  },
  {
    courseCode: "DOM-MCB 214",
    programme: ["microbiology"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "12:00" }],
    lecturer: "Ms. Oloruntoba",
    venue: "CAS 1",
  },
  {
    courseCode: "CHM 302",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "12:00" }],
    lecturer: "Mr Olaniran",
    venue: "LO",
  },
  {
    courseCode: "BCH 416",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "12:00" }],
    lecturer: "Dr Olaleye",
    venue: "CSL",
  },
  {
    courseCode: "CHM 420",
    programme: ["biochemistry"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "12:00" }],
    lecturer: "Dr Olojo/Mrs Oyelahan",
    venue: "LO",
  },
  {
    courseCode: "BCH 316",
    programme: ["biochemistry"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "12:00" }],
    lecturer: "Mr John",
    venue: "CAS 2",
  },
  {
    courseCode: "MCB 324",
    programme: ["microbiology"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Taylor",
    venue: "MBL",
  },
  {
    courseCode: "CSC 310",
    programme: ["computer science"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Ms Aromavo",
    venue: "HL",
  },
  {
    courseCode: "CSC 406",
    programme: ["computer science"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "09:15", endTime: "10:15" }],
    lecturer: "Ms Ayediran",
    venue: "SL",
  },
  {
    courseCode: "SEN 306",
    programme: ["software engineering"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "09:15", endTime: "10:15" }],
    lecturer: "Ms Ayediran",
    venue: "SL",
  },
  {
    courseCode: "DOM-CYB 206",
    programme: ["cyber security"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "12:00" }],
    lecturer: "Mr Okunlola",
    venue: "CAS 3",
  },
  {
    courseCode: "DOM-CSC 204",
    programme: ["computer science"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "12:00" }],
    lecturer: "Dr Ayeni",
    venue: "HL",
  },
];

export const courses_fasms = [

  // ==================== MONDAY (day: 1) ====================

  {
    courseCode: "GST 212",
    programme: ["accounting", "business administration", "economics", "mass communication", "criminology and security studies", "industrial and personnel management"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mrs Olanisebe",
    venue: "CAS 3",
  },
  {
    courseCode: "MGT 322",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Oshevire",
    venue: "NR",
  },
  {
    courseCode: "ACC 426",
    programme: ["accounting"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr Olayinka",
    venue: "ENT",
  },
  {
    courseCode: "ECO 408",
    programme: ["economics"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr Oyedele",
    venue: "LO",
  },
  {
    courseCode: "ECO 310",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Adekanbi",
    venue: "LO",
  },
  {
    courseCode: "CRM 312",
    programme: ["criminology and security studies"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Imaledo",
    venue: "ASM 1",
  },
  {
    courseCode: "MAS 402",
    programme: ["mass communication"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Victor-Tade",
    venue: "ASM 2",
  },
  {
    courseCode: "DOM-COM 202",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Ms Aluko",
    venue: "ASM 3",
  },
  {
    courseCode: "ACC 325",
    programme: ["accounting"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mrs Udeme",
    venue: "NR",
  },
  {
    courseCode: "ECO 414",
    programme: ["economics"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Adekanbi",
    venue: "LO",
  },
  {
    courseCode: "BUS 410",
    programme: ["business administration"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Alabi",
    venue: "LO",
  },
  {
    courseCode: "ECO 312",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Oyedele",
    venue: "LO",
  },
  {
    courseCode: "CSS 204",
    programme: ["criminology and security studies"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Aruoture",
    venue: "ASM 1",
  },
  {
    courseCode: "CRM 304",
    programme: ["criminology and security studies"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mrs Olanisebe",
    venue: "ASM 2",
  },
  {
    courseCode: "DOM-ACC 202",
    programme: ["accounting"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Udeme",
    venue: "ASM 1",
  },
  {
    courseCode: "BUA 202/DOM-BUA 202",
    programme: ["business administration"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr Oluwajinmi",
    venue: "LO",
  },
  {
    courseCode: "BUS 318",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr. Oshevire",
    venue: "NR",
  },
  {
    courseCode: "DOM-IRP 122/DOM-PSY 201",
    programme: ["industrial and personnel management"],
    level: "100",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Aruoture",
    venue: "LT",
  },
  {
    courseCode: "ACC 323",
    programme: ["accounting"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr Olayinka",
    venue: "ASM 2",
  },
  {
    courseCode: "ACC 422",
    programme: ["accounting"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Ms Fanimokun",
    venue: "ASM 2",
  },
  {
    courseCode: "BUA 218",
    programme: ["business administration"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Alabi",
    venue: "LO",
  },
  {
    courseCode: "ACC 302",
    programme: ["accounting"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Ms Fanimokun",
    venue: "ASM 1",
  },
  {
    courseCode: "CSS 104",
    programme: ["criminology and security studies"],
    level: "100",
    dayAndTime: [{ day: 1, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Mr Aruoture",
    venue: "ASM 2",
  },
  {
    courseCode: "DOM-MAS 202",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Victor-Tade",
    venue: "ASM 4",
  },
  {
    courseCode: "MAS 416",
    programme: ["mass communication"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Mr Afolabi",
    venue: "ENT",
  },
  {
    courseCode: "MAS 310",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 1, startTime: "16:00", endTime: "18:00" }],
    lecturer: "Dr. Iloh",
    venue: "ASM 1",
  },
  {
    courseCode: "CRM 402",
    programme: ["criminology and security studies"],
    level: "400",
    dayAndTime: [{ day: 1, startTime: "16:00", endTime: "18:00" }],
    lecturer: "Dr. Tekene",
    venue: "ASM 3",
  },

  // ==================== TUESDAY (day: 2) ====================

  {
    courseCode: "MAS 402",
    programme: ["mass communication"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Victor-Tade",
    venue: "ASM 2",
  },
  {
    courseCode: "MAS 324",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mrs Sam-Olaniyan",
    venue: "ASM 3",
  },
  {
    courseCode: "AMS 102/ECO 104",
    programme: ["economics"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Opadeji",
    venue: "ASM 4",
  },
  {
    courseCode: "DOM-ACC 202",
    programme: ["accounting"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mrs Udeme",
    venue: "ASM 1",
  },
  {
    courseCode: "ECO 308",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Opadeji",
    venue: "LO",
  },
  {
    courseCode: "CRM 410",
    programme: ["criminology and security studies"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Akoma",
    venue: "ASM 2",
  },
  {
    courseCode: "MAS 410",
    programme: ["mass communication"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Iloh",
    venue: "ASM 3",
  },
  {
    courseCode: "MCM 210",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Biyi Alabi",
    venue: "NR",
  },
  {
    courseCode: "MCM 206",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Afolabi",
    venue: "LO",
  },
  {
    courseCode: "ACC 102/DOM-ACC 102",
    programme: ["accounting"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mrs Udeme",
    venue: "ENT",
  },
  {
    courseCode: "MAS 318",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Iloh",
    venue: "LO",
  },
  {
    courseCode: "EHR 208",
    programme: ["industrial and personnel management"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Alase",
    venue: "LO",
  },
  {
    courseCode: "DOM-CRM 108",
    programme: ["criminology and security studies"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Barrister Adetoyinbo",
    venue: "CAS 2",
  },
  {
    courseCode: "ACC 402",
    programme: ["accounting"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Prof. Ewetade",
    venue: "LO",
  },
  {
    courseCode: "BUA 102",
    programme: ["business administration"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr. Oshevire",
    venue: "ASM 2",
  },
  {
    courseCode: "ECO 328",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr Oyedele",
    venue: "LO",
  },
  {
    courseCode: "MGT 320/IRP 314",
    programme: ["business administration", "industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Alabi",
    venue: "FL",
  },
  {
    courseCode: "EHR 206",
    programme: ["industrial and personnel management"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr Oluwajinmi",
    venue: "LO",
  },
  {
    courseCode: "CRM 416",
    programme: ["criminology and security studies"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Barrister Adetoyinbo",
    venue: "FL",
  },
  {
    courseCode: "MAS 304",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr Alade",
    venue: "ASM 4",
  },
  {
    courseCode: "CMS 102",
    programme: ["industrial and personnel management"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Afolabi",
    venue: "ENT",
  },
  {
    courseCode: "MCM 208",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Biyi Alabi",
    venue: "ASM 3",
  },
  {
    courseCode: "MCM 212",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Iloh",
    venue: "ASM 4",
  },
  {
    courseCode: "CRM 322",
    programme: ["criminology and security studies"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Aruoture",
    venue: "ENT",
  },
  {
    courseCode: "EHR 202",
    programme: ["industrial and personnel management"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Jonah",
    venue: "LO",
  },
  {
    courseCode: "IRP 318",
    programme: ["industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "11:15", endTime: "12:15" }],
    lecturer: "Dr. Alase",
    venue: "LO",
  },
  {
    courseCode: "BUS 414",
    programme: ["business administration"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Alabi",
    venue: "FL",
  },
  {
    courseCode: "ACC 206/ACC 327",
    programme: ["accounting"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr Olayinka",
    venue: "ASM 1",
  },
  {
    courseCode: "CSS 102",
    programme: ["criminology and security studies"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs. Olanisebe",
    venue: "ASM 3",
  },
  {
    courseCode: "MCM 216",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Sam-Olaniyan",
    venue: "ASM 4",
  },
  {
    courseCode: "ECO 206",
    programme: ["economics"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Mr. Olusegun Alfred",
    venue: "FL",
  },
  {
    courseCode: "MCM 202",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Victor-Tade",
    venue: "ASM 4",
  },
  {
    courseCode: "IRP 406/IRP 310",
    programme: ["industrial and personnel management"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Dr. Olayinka",
    venue: "LO",
  },
  {
    courseCode: "DOM-CRM 106",
    programme: ["criminology and security studies"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Tekene",
    venue: "LT",
  },
  {
    courseCode: "BUS 314",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Mr. Oshevire",
    venue: "FL",
  },
  {
    courseCode: "ECO 304",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr Oyedele",
    venue: "LO",
  },
  {
    courseCode: "EHR 208",
    programme: ["industrial and personnel management"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Alase",
    venue: "LO",
  },
  {
    courseCode: "MAS 312",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Alade",
    venue: "ASM 1",
  },
  {
    courseCode: "CSS 206",
    programme: ["criminology and security studies"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Akoma",
    venue: "ASM 3",
  },
  {
    courseCode: "MCM 102/MAS 208",
    programme: ["mass communication"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Iloh",
    venue: "ASM 3",
  },
  {
    courseCode: "ACC 424",
    programme: ["accounting"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Prof. Ewetade",
    venue: "LO",
  },
  {
    courseCode: "MAS 412",
    programme: ["mass communication"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Mrs Sam-Olaniyan",
    venue: "ASM 2",
  },
  {
    courseCode: "MCM 204/MAS 203",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr Alade",
    venue: "ASM 3",
  },
  {
    courseCode: "ACC 422",
    programme: ["accounting"],
    level: "400",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Ms Fanimokun",
    venue: "ASM 4",
  },
  {
    courseCode: "CSS 104",
    programme: ["criminology and security studies"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "14:00", endTime: "15:00" }],
    lecturer: "Mr Aruoture",
    venue: "LT",
  },

  // ==================== WEDNESDAY (day: 3) ====================

  {
    courseCode: "ECO 202",
    programme: ["economics"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr. Adekanbi",
    venue: "LO",
  },
  {
    courseCode: "SSC 202",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Ms Ayediran/Mr Egor",
    venue: "SL",
  },
  {
    courseCode: "BUS 312",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr Oluwajinmi",
    venue: "FL",
  },
  {
    courseCode: "DOM-CSS 210",
    programme: ["criminology and security studies"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Aruotur",
    venue: "ASM 1",
  },
  {
    courseCode: "BUA 216",
    programme: ["business administration"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Ms Fanimokun",
    venue: "LO",
  },
  {
    courseCode: "CRM 310",
    programme: ["criminology and security studies"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Barrister Adetoyinbo",
    venue: "ASM 3",
  },
  {
    courseCode: "ACC 206/ACC 327",
    programme: ["accounting"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr Olayinka",
    venue: "ASM 4",
  },
  {
    courseCode: "BUA 216",
    programme: ["business administration"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Ms Fanimokun",
    venue: "LO",
  },
  {
    courseCode: "BUS 306",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Alabi",
    venue: "LO",
  },
  {
    courseCode: "ACC 323",
    programme: ["accounting"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr Olayinka",
    venue: "NR",
  },
  {
    courseCode: "ECO 426",
    programme: ["economics"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Adekanbi",
    venue: "LO",
  },
  {
    courseCode: "CRM 412",
    programme: ["criminology and security studies"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Imaledo",
    venue: "ASM 1",
  },
  {
    courseCode: "DOM-CSS 208",
    programme: ["criminology and security studies"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Tekene",
    venue: "ASM 2",
  },
  {
    courseCode: "ACC 204/DOM-ACC 204",
    programme: ["accounting"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Udeme",
    venue: "ASM 1",
  },
  {
    courseCode: "MGT 320",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Alabi",
    venue: "NR",
  },
  {
    courseCode: "BUS 404",
    programme: ["business administration"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr Oluwajinmi",
    venue: "LO",
  },
  {
    courseCode: "MAS 316",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Dr. Alade",
    venue: "ENT",
  },
  {
    courseCode: "DOM-IRP 122/DOM-PSY 201",
    programme: ["industrial and personnel management"],
    level: "100",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Aruoture",
    venue: "LT",
  },
  {
    courseCode: "DOM-ECO 204",
    programme: ["economics"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr Adekanmbi",
    venue: "ENT",
  },
  {
    courseCode: "BUS 318",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Mr. Oshevire",
    venue: "FL",
  },
  {
    courseCode: "AMS 104",
    programme: ["economics"],
    level: "100",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr Olayinka",
    venue: "LO",
  },
  {
    courseCode: "ECO 404",
    programme: ["economics"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr Oyedele",
    venue: "LO",
  },
  {
    courseCode: "CRM 404",
    programme: ["criminology and security studies"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr Afatakpa/Mrs. Olanisebe",
    venue: "ASM 1",
  },
  {
    courseCode: "MAS 408",
    programme: ["mass communication"],
    level: "400",
    dayAndTime: [{ day: 3, startTime: "16:00", endTime: "18:00" }],
    lecturer: "Dr Iloh",
    venue: "ASM 4",
  },
  {
    courseCode: "CRM 316",
    programme: ["criminology and security studies"],
    level: "300",
    dayAndTime: [{ day: 3, startTime: "16:00", endTime: "18:00" }],
    lecturer: "Dr. Tekene",
    venue: "ASM 3",
  },

  // ==================== THURSDAY (day: 4) ====================

  {
    courseCode: "GST 112",
    programme: ["accounting", "business administration", "economics", "mass communication", "criminology and security studies", "industrial and personnel management"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Akoma",
    venue: "CAS 3",
  },
  {
    courseCode: "BUS 414",
    programme: ["business administration"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Alabi",
    venue: "LO",
  },
  {
    courseCode: "DOM-LAW 202",
    programme: ["business administration"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr. Oshevire",
    venue: "NR",
  },
  {
    courseCode: "ECO 316",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Olaleye",
    venue: "FL",
  },
  {
    courseCode: "IRP 320",
    programme: ["industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Ms Fanimokun",
    venue: "LO",
  },
  {
    courseCode: "CSS 202",
    programme: ["criminology and security studies"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Barrister Adetoyinbo",
    venue: "ASM 3",
  },
  {
    courseCode: "MAS 404",
    programme: ["mass communication"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Shoroye",
    venue: "ASM 4",
  },
  {
    courseCode: "SSC 202",
    programme: ["computer science", "cyber security", "software engineering"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "09:15", endTime: "10:15" }],
    lecturer: "Ms Ayediran/Mr Egor",
    venue: "SL",
  },
  {
    courseCode: "MCM 320",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Shoroye",
    venue: "NR",
  },
  {
    courseCode: "DOM-CSS 214",
    programme: ["criminology and security studies"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mrs Olanisebe",
    venue: "ASM 4",
  },
  {
    courseCode: "DOM-MAS 104",
    programme: ["mass communication"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Victor-Tade",
    venue: "ENT",
  },
  {
    courseCode: "DOM-ECO 102/ECO 102",
    programme: ["economics"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Opadeji",
    venue: "ASM 1",
  },
  {
    courseCode: "DOM-ECO 210",
    programme: ["economics"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Olaleye",
    venue: "FL",
  },
  {
    courseCode: "ACC 204/DOM-ACC 204",
    programme: ["accounting"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mrs Udeme",
    venue: "ASM 2",
  },
  {
    courseCode: "MAS 314",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Afolabi",
    venue: "ASM 4",
  },
  {
    courseCode: "CRM 308",
    programme: ["criminology and security studies"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Akoma",
    venue: "ASM 3",
  },
  {
    courseCode: "DOM-CRM 102",
    programme: ["criminology and security studies"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Tekene",
    venue: "ENT",
  },
  {
    courseCode: "MCM 322",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Aruoture",
    venue: "ENT",
  },
  {
    courseCode: "EHR 202",
    programme: ["industrial and personnel management"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Jonah",
    venue: "LO",
  },
  {
    courseCode: "IRP 318",
    programme: ["industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "11:15", endTime: "12:15" }],
    lecturer: "Dr. Alase",
    venue: "LO",
  },
  {
    courseCode: "ECO 306",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Opadeji",
    venue: "NR",
  },
  {
    courseCode: "BUA/DOM-BUA 204",
    programme: ["business administration"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Olayinka",
    venue: "ASM 2",
  },
  {
    courseCode: "ECO 302",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Olaleye",
    venue: "FL",
  },
  {
    courseCode: "BUS 410",
    programme: ["business administration"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Alabi",
    venue: "NR",
  },
  {
    courseCode: "MAS 302",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Afolabi",
    venue: "ENT",
  },
  {
    courseCode: "ECO 402",
    programme: ["economics"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Olaleye",
    venue: "FL",
  },
  {
    courseCode: "BUA 202/DOM-BUA 202",
    programme: ["business administration"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Oluwajimi",
    venue: "LO",
  },
  {
    courseCode: "MGT 302",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr Alabi",
    venue: "ASM 1",
  },
  {
    courseCode: "CRM 408",
    programme: ["criminology and security studies"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Imaledo",
    venue: "ASM 3",
  },
  {
    courseCode: "MAS 306",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Victor-Tade",
    venue: "ASM 4",
  },
  {
    courseCode: "MCM 104",
    programme: ["mass communication"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Alade",
    venue: "ENT",
  },
  {
    courseCode: "ECO 420",
    programme: ["economics"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Opadeji",
    venue: "LO",
  },
  {
    courseCode: "ACC 302",
    programme: ["accounting"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Ms Fanimokun",
    venue: "FL",
  },
  {
    courseCode: "MCM 214",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mrs Sam-Olaniyan",
    venue: "ASM 1",
  },
  {
    courseCode: "MAS 308",
    programme: ["mass communication"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr Shoroye",
    venue: "ASM 2",
  },
  {
    courseCode: "DOM-ECO 106",
    programme: ["economics"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Adekanbi",
    venue: "LO",
  },
  {
    courseCode: "IRP 316",
    programme: ["industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Alase",
    venue: "LO",
  },
  {
    courseCode: "DOM-MAS 204",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr. Afolabi",
    venue: "ENT",
  },
  {
    courseCode: "IRP 318",
    programme: ["industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "11:15", endTime: "12:15" }],
    lecturer: "Dr. Alase",
    venue: "LO",
  },
  {
    courseCode: "MCM 106",
    programme: ["mass communication"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Miss Aluko",
    venue: "ASM 4",
  },
  {
    courseCode: "ACC 102/DOM-ACC 102",
    programme: ["accounting"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Udeme",
    venue: "ASM 3",
  },
  {
    courseCode: "CRM 406",
    programme: ["criminology and security studies"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Tekene",
    venue: "ASM 1",
  },
  {
    courseCode: "IRP 312",
    programme: ["industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "17:00" }],
    lecturer: "Digital skill Acquisition",
    venue: "LT",
  },
  {
    courseCode: "CRM 302",
    programme: ["criminology and security studies"],
    level: "300",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Barrister Adetoyinbo",
    venue: "ASM 2",
  },
  {
    courseCode: "MAS 414",
    programme: ["mass communication"],
    level: "400",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Shoroye",
    venue: "ASM 3",
  },
  {
    courseCode: "DOM-MAS 206",
    programme: ["mass communication"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Dr. Alade",
    venue: "ASM 4",
  },

  // ==================== FRIDAY (day: 5) ====================

  {
    courseCode: "ECO 314",
    programme: ["economics"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Adekanbi",
    venue: "LO",
  },
  {
    courseCode: "IRP 316",
    programme: ["industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "09:15", endTime: "11:15" }],
    lecturer: "Dr Alase",
    venue: "LO",
  },
  {
    courseCode: "BUS 404",
    programme: ["business administration"],
    level: "400",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr Oluwajinmi",
    venue: "LO",
  },
  {
    courseCode: "DOM-CSS 212",
    programme: ["criminology and security studies"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mrs Olanisebe",
    venue: "ASM 2",
  },
  {
    courseCode: "CSS 102",
    programme: ["criminology and security studies"],
    level: "100",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mrs. Olanisebe",
    venue: "ASM 1",
  },
  {
    courseCode: "DOM-ECO 212",
    programme: ["economics"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr Oyedele",
    venue: "FL",
  },
  {
    courseCode: "BUA/DOM-BUA 204",
    programme: ["business administration"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Olayinka",
    venue: "LO",
  },
  {
    courseCode: "BUS 322",
    programme: ["business administration"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr. Oshevire",
    venue: "NR",
  },
  {
    courseCode: "IRP 312",
    programme: ["industrial and personnel management"],
    level: "300",
    dayAndTime: [{ day: 5, startTime: "14:00", endTime: "17:00" }],
    lecturer: "Digital skill Acquisition",
    venue: "LT",
  },
];

export const courses_fahs = [

  // ==================== MONDAY (day: 1) ====================

  {
    courseCode: "BIO 102",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Akoun/Mrs Oluwajinmi",
    venue: "LT",
  },
  {
    courseCode: "NSC 206",
    programme: ["nursing"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Ajileye",
    venue: "FAHS I",
  },
  {
    courseCode: "PHS 204",
    programme: ["nursing", "public health"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Olusegun Alfred",
    venue: "FAHS I",
  },
  {
    courseCode: "ANA 204",
    programme: ["nursing"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "11:15", endTime: "12:15" }],
    lecturer: "Dr. Balogun",
    venue: "FAHS I",
  },
  {
    courseCode: "DOM-MLS 204",
    programme: ["MLS"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Ajileye",
    venue: "FAHS II",
  },
  {
    courseCode: "CHM 108",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 1, startTime: "14:00", endTime: "17:00" }],
    lecturer: "Mrs Hassan",
    venue: "CSL",
  },
  {
    courseCode: "DOM-IRP 122/DOM-PSY 201",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Aruoture",
    venue: "LT",
  },
  {
    courseCode: "ANA 204",
    programme: ["nursing"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Dr. Balogun",
    venue: "FAHS I",
  },
  {
    courseCode: "ANA 202",
    programme: ["nursing"],
    level: "200",
    dayAndTime: [{ day: 1, startTime: "15:00", endTime: "17:00" }],
    lecturer: "Dr. Balogun",
    venue: "FAHS I",
  },

  // ==================== TUESDAY (day: 2) ====================

  {
    courseCode: "GST 112",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Imaledo",
    venue: "LT",
  },
  {
    courseCode: "DOM-PHE 206",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "08:15", endTime: "09:15" }],
    lecturer: "MS Arewa",
    venue: "FAHS II",
  },
  {
    courseCode: "BCH 202",
    programme: ["nursing", "MLS"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr. Olaleye/Mr Akinboro",
    venue: "CSL",
  },
  {
    courseCode: "PHS 204",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mrs John",
    venue: "FAHS II",
  },
  {
    courseCode: "BIO 108",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mrs Oyelahan",
    venue: "MBL",
  },
  {
    courseCode: "NSC 202",
    programme: ["nursing"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Nurses Kolade & Lawal",
    venue: "FAHS 1",
  },
  {
    courseCode: "DOM-PHE 212",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 2, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Ms Arewa",
    venue: "FAHS II",
  },

  // ==================== WEDNESDAY (day: 3) ====================

  {
    courseCode: "GST 212",
    programme: ["nursing", "public health", "MLS"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Dr. Imaledo",
    venue: "LT",
  },
  {
    courseCode: "DOM-NSC 102/MTH 102",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mr Ajayi",
    venue: "LT",
  },
  {
    courseCode: "PIO 212",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Ms Oyelade",
    venue: "FAHS I",
  },
  {
    courseCode: "PSY 201/DOM-PSY 201/DOM-MLS 122",
    programme: ["nursing", "public health", "MLS"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Mr Aruoture",
    venue: "ENT",
  },
  {
    courseCode: "PIO 214",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Ms Oyelade",
    venue: "FAHS II",
  },
  {
    courseCode: "PHY 108",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 3, startTime: "14:00", endTime: "17:00" }],
    lecturer: "Mr Akingba",
    venue: "HL",
  },
  {
    courseCode: "PIO 216",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 3, startTime: "15:00", endTime: "17:00" }],
    lecturer: "Ms Oyelade",
    venue: "FAHS II",
  },

  // ==================== THURSDAY (day: 4) ====================

  {
    courseCode: "PHY 102",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr Iwasokun",
    venue: "LT",
  },
  {
    courseCode: "NSC 202",
    programme: ["nursing"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Dr Olabisi/Dr. Bello/Mrs Azeez",
    venue: "FAHS 1",
  },
  {
    courseCode: "DOM-PHE 208",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Mrs John",
    venue: "FAHS II",
  },
  {
    courseCode: "DOM-NSC 202",
    programme: ["nursing"],
    level: "200",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "15:00" }],
    lecturer: "Dr. Bello/Mrs Azeez",
    venue: "FAHS 1",
  },
  {
    courseCode: "DOM-MCB 102/DOM-NSC/MLS 104",
    programme: ["nursing", "MLS"],
    level: "100",
    dayAndTime: [{ day: 4, startTime: "13:00", endTime: "14:00" }],
    lecturer: "Dr. Taylor/Mrs Olayinka",
    venue: "LT",
  },

  // ==================== FRIDAY (day: 5) ====================

  {
    courseCode: "CHM 102/DOM-CHM 102",
    programme: ["nursing", "public health", "MLS"],
    level: "100",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Mr John/Mrs Oyelahan",
    venue: "LT",
  },
  {
    courseCode: "DOM-PHE 210",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "08:15", endTime: "09:15" }],
    lecturer: "Ms Arewa",
    venue: "Field work",
  },
  {
    courseCode: "NSC 202",
    programme: ["nursing"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Nurses Lawal & Kolade",
    venue: "FAHS 1",
  },
  {
    courseCode: "DOM-PHE 210",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "10:15", endTime: "11:15" }],
    lecturer: "Ms Arewa",
    venue: "Field work",
  },
  {
    courseCode: "DOM-MLS 202",
    programme: ["MLS"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "15:00", endTime: "17:00" }],
    lecturer: "Dr Adewole",
    venue: "FAHS 1",
  },
  {
    courseCode: "DOM-PHE 210",
    programme: ["public health"],
    level: "200",
    dayAndTime: [{ day: 5, startTime: "14:00", endTime: "16:00" }],
    lecturer: "Ms Arewa",
    venue: "Field work",
  },
];

export const courses = [...courses_fasms,...courses_fcas,...courses_fahs]